### ISSUE TITLE
Airdrop mainnet checklist

### ISSUE THREAD

**Issue by etienne-napoleone** [orne-io/contracts#4]
- [x] Add 235 uORNE to the company address for a round airdrop
- [x] generate airdrop.json
- [x] generate merkle root `dffb34987ee157f8ff1cd0a4c6e80c06555c17da326370c397c379947017b96c`
- [x] instantiate cw20 token
- [x] instantiate airdrop contract
```json
{
  "merkle_root": "dffb34987ee157f8ff1cd0a4c6e80c06555c17da326370c397c379947017b96c",
  "airdrop_size": "100000000000000",
  "to_timestamp": 1664575199,
  "token_address": "terra19p20mfnvwh9yvyr7aus3a6z6g6uk28fv4jhx9kmnc2m7krg27q2qkfenjw"
}
```
- [x] transfer full supply to airdrop contract
- [ ] add token address to [terra assets](https://github.com/terra-money/assets)
